mysql:
  host: 'localhost'
  user: 'ads_test'
  password: 'ads_test'
  database: 'ads_test'
redmine:
  host: "localhost"
  port: 3030
  basePath: "/"
  apiKey: "GET API KEY FROM REDMINE"
  projectId: 1
test:
  database:
    tables:
      - 'access_log'
      - 'dcase_tag_rel'
      - 'tag'
      # - 'monitor_node'
      # - 'issue'
      - 'node'
      - 'commit'
      - 'dcase'
      - 'file'
      - 'project_has_user'
      - 'project'
      - 'user'
