exports.lang = {
    ja: {
        home: "ホーム",
        edit: "編集",
        undo: "元に戻す",
        redo: "やり直し",
        export: "エクスポート",
        JSON: "JSON",
        PNG: "PNG",
        PDF: "PDF",
        DScript: "D-Script",
        commit: "コミット",
        commitlog: "コミット履歴",
        config: "設定",
        color_theme: "カラーテーマの変更",
        locale: "言語の変更",
        new_DCase: "新しいCaseを作成する",
        new_Project: "新しいProjectを作成する",
        DCase_name: "Case名",
        Project_name: "Project名",
        creater: "作成者",
        topgoal: "TopGoalの説明",
        last_commit: "最終コミット日時",
        last_commiter: "最終コミット者",
        create: "作成",
        cut: "切り取り",
        copy: "コピー",
        paste: "貼り付け",
        delete: "削除",
        openall: "全て開く",
        closeall: "全て折りたたむ",
        locale: "言語設定",
        SelectCase: "Case選択",
        AllTags: "全てのタグを表示",
        member: "メンバー",
        public: "公開プロジェクト"
    },
    en: {
        home: "Home",
        edit: "Edit",
        undo: "Undo",
        redo: "Redo",
        export: "Export",
        JSON: "JSON",
        PNG: "PNG",
        PDF: "PDF",
        DScript: "D-Script",
        commit: "Commit",
        commitlog: "History",
        config: "Configuration",
        color_theme: "Theme",
        locale: "Language",
        new_DCase: "Create a new Case",
        new_Project: "Create a new Project",
        DCase_name: "Case Name",
        Project_name: "Project Name",
        topgoal: "Description of the Top Goal",
        create: "Create",
        creater: "Owner",
        last_commit: "Last commit date",
        last_commiter: "Last commiter",
        cut: "Cut",
        paste: "Paste",
        copy: "Copy",
        delete: "Delete",
        openall: "Open all",
        closeall: "Close all",
        locale: "Language",
        SelectCase: "Select Case",
        AllTags: "Show all tags",
        member: "Member",
        public: "Public project"
    }
};

