#!/bin/sh
#
# chkconfig: 345 99 99
# description: ADS
#

. /etc/rc.d/init.d/functions

NODE_ENV=production
NODE_CONFIG_DIR=/usr/local/assureit/ads/app/config
user="apache" # 実行するユーザー

nodejs="/usr/bin/node" # Node.jsのパス
rootdir="/usr/local/assureit/ads/app" #app.jsがあるパス

server="$rootdir/app.js" # サーバへのパス

logfile="/var/log/assureit/ads.log" # ログファイルのパス

lockfile="/var/lock/subsys/ads" # ロックファイルへのパス

start()
{
    if [ ! -f $lockfile ] ; then
        echo -n $"Starting $server: "
        runuser -l "$user" -c "NODE_ENV=$NODE_ENV NODE_CONFIG_DIR=$NODE_CONFIG_DIR nohup $nodejs $server >> $logfile &" && echo_success || echo_failure
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch $lockfile
    else
        echo "$server is locked."
        RETVAL=1
    fi
}

stop()
{
    echo -n $"Stopping $server: "
    pid=`ps -aefw | grep "$nodejs $server" | grep -v " grep " | awk '{print $2}'`
    kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure

    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        RETVAL=1
esac

exit $RETVAL